### ISSUE TITLE
Unable to run unit tests with jest

### ISSUE THREAD

**Issue by nevestuan** [iiroj/use-breakpoint#13]
Hi, I am facing an error when using the hook in a Nx typescript mono project. The tests are getting failed with the following error:

```
  Details:

    /Users/tuan/Code/carro-internal-web/node_modules/use-breakpoint/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import useBreakpoint from './useBreakpoint.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import useBreakpoint from 'use-breakpoint';
 ```
    
 Could anyone please advise? Thanks.

**Comment by iiroj** [comment]
Hey, this is an ESM module so you'll need to setup some transpilation for it in the Jest config.

**Comment by rdiazv** [comment]
Hi @iiroj! It would be helpful to have some setup example for jest, I tried to make it work without luck so I had to look for another alternative :(

Thanks for putting the work on this lib, it's great!

**Comment by iiroj** [comment]
I found this issue, maybe it's relevant: https://github.com/nrwl/nx/issues/7170

In the end, you might need something like this in your Jest config:

```
  transformIgnorePatterns: ['node_modules/(?!use-breakpoint/)'],
```

It means "ignore everything under `node_modules/` except `node_modules/use-breakpoint/`
