### ISSUE TITLE
deprecation of MediaQueryList#addListerner

### ISSUE THREAD

**Issue by espretto** [iiroj/use-breakpoint#14]
Hi,
there has been a change to the API and support for the old one may be dropped soon: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

This afftects code at https://github.com/iiroj/use-breakpoint/blob/2fe26c3c7b9ea25050c7ff1c289d0cbbc357ee9c/useBreakpoint.ts#L109

I really like this hook being SSR-aware!

**Comment by iiroj** [comment]
Hey, thanks for the issue! Can you check out if the linked PR makes sense? Seemed to work fine when I tested it.

**Comment by espretto** [comment]
Great, yes #15 fixes this.

**Comment by iiroj** [comment]
Just pushed `3.0.4` to implement this. Thanks, been meaning to do it since the beginning but never got around to it.
