### ISSUE TITLE
Incorrect repository URL in package.json

### ISSUE THREAD

**Issue by devklick** [iiroj/use-breakpoint#23]
The URL you have listed in your [package.json](https://github.com/iiroj/use-breakpoint/blob/8512302ffacc025a735369d6ed15eaa8a910965e/package.json#L10) points to the wrong repository. It points to https://github.com/iiroj/iiro.fi instead of https://github.com/iiroj/use-breakpoint. This is confusing when navigating from NPM, because the repository links takes the user to _different code_, rather than the code for the package.

Going by the [NPM package.json schema](https://github.com/iiroj/use-breakpoint), the purpose of the repository property is to:
>Specify the place where your code lives

**Comment by iiroj** [comment]
Oops, I have copy-pasted some of the package.json config incorrectly from my other repo; thanks will fix!
