### ISSUE TITLE
always returns default breakpoint

### ISSUE THREAD

**Issue by olsonpm** [iiroj/use-breakpoint#25]
Here's a codesandbox showing the issue
https://codesandbox.io/p/sandbox/jolly-framework-2gy2zd

![use-breakpoint-issue](https://github.com/user-attachments/assets/68bba1e4-cda5-41aa-b446-7d5d9f0d87d3)

**Comment by iiroj** [comment]
Hello, does it work in 4.0.1 but is broken in 4.0.2?

**Comment by olsonpm** [comment]
feel free to specify the version in codesandbox.  I ended up rolling my own solution - hitting this issue was kinda frustrating so i'm not going to debug further.

**Comment by iiroj** [comment]
Thanks for the issue anyway, I'll fix it it.

I also try to avoid this library and stick to pure CSS solutions nowadays...

**Comment by olsonpm** [comment]
it is nice when css solutions are possible.  I needed this for nivo which is a graph library where theming is js based

**Comment by iiroj** [comment]
I can see that it doesn't work in your Codesandbox.io, but I can't really debug it further since I don't want to register a user account there. The Storybook setup in this repo is working fine, can you try cloning that to verify?

```shell
git clone git@github.com:iiroj/use-breakpoint.git
cd use-breakpoint
npm ci
npm start
```

EDIT: I was able to replicate the bug in Storybook by copy-pasting your codesanbox example component!

**Comment by olsonpm** [comment]
I'm able to reproduce by changing the default from 'mobile' to 'desktop' in your main branch

**Comment by iiroj** [comment]
Yes, the bug is because of the `Array.find()` finding the default breakpoint value from the list of media queries first, since they are sorted by size. Thus it doesn't hit the actual value, but the default instead... I will open a PR.

**Comment by iiroj** [comment]
As is customary when configuring `npm`, I had some trouble with releasing using the new provenance feature... but 4.0.5 should now be available with a fix to this issue; thanks!
