### ISSUE TITLE
Maximum update depth error spam

### ISSUE THREAD

**Issue by henriquecolini** [iiroj/use-breakpoint#6]
I just copied the sample code from the npm page and ran:

```jsx
import useBreakpoint from 'use-breakpoint';
 
const CurrentBreakpoint = () => {
  const {
    breakpoint,
    maxWidth,
    minWidth 
  } = useBreakpoint(
    { mobile: 0, tablet: 768, desktop: 1280 },
    'desktop'
  );
 
  return (
    <p>The current breakpoint is {breakpoint}!</p>
  );
};

function App() {
  return <CurrentBreakpoint/>;
}
```

And in the console. I got an infinite spam of the maximum update depth error.

`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

![image](https://user-images.githubusercontent.com/5795764/97117542-2fc8ad00-16e3-11eb-9fda-a6e8f87863a0.png)

I tried changing breakpoints, using useBreakpoint() in other components, and this always happened. Seems to me like there's something fundamentally broken in the code. I'm on React 16.14.0. I used CRA.

**Comment by iiroj** [comment]
Let me take look... I don't personally use this hook, so I'm sorry it's not received the proper care.

**Comment by iiroj** [comment]
Related: https://github.com/iiroj/use-breakpoint/issues/3

**Comment by iiroj** [comment]
Hello, it might be that in your example, the infinite loop is caused by the inline object `{ mobile: 0, tablet: 768, desktop: 1280 }`. In JavaScript, declaring new objects in the function argument means that it's a new object every time.

Try hoisting the object to a variable outside the component body:

```js
const BREAKPOINTS = { mobile: 0, tablet: 768, desktop: 1280 }
```

EDIT: I will update the README accordingly.
